import { Link } from "react-router-dom";

import LegalPage, { LegalList, Strong, type LegalSection } from "@/components/site/LegalPage";
import { usePageTitle } from "@/hooks/use-page-title";
import { SITE } from "@/lib/site";

const email = (
  <a href={`mailto:${SITE.supportEmail}`} className="text-link break-all">
    {SITE.supportEmail}
  </a>
);

const SECTIONS: ReadonlyArray<LegalSection> = [
  {
    id: "agreement",
    title: "Agreement",
    body: (
      <p>
        These Terms of Use ("Terms") are an agreement between you and {SITE.company} ("we", "us") covering your use of
        the {SITE.product} app and this website (together, the "Service"). By downloading or using the Service, you agree
        to these Terms and our{" "}
        <Link to="/privacy" className="text-link">
          Privacy Policy
        </Link>
        . If you don't agree, please don't use the Service.
      </p>
    ),
  },
  {
    id: "license",
    title: "Your license to use Paddle Up",
    body: (
      <p>
        We grant you a personal, non-exclusive, non-transferable, revocable license to use {SITE.product} on Apple
        devices you own or control, for your own non-commercial practice, as permitted by the App Store's Usage Rules. We
        and our licensors own the Service, including its software, scoring models, coaching content and design.
      </p>
    ),
  },
  {
    id: "acceptable-use",
    title: "Acceptable use",
    body: (
      <>
        <p>When using the Service, you agree not to:</p>
        <LegalList
          items={[
            "Copy, modify, reverse engineer, decompile or resell the app or its scoring models, except where the law expressly allows it.",
            "Interfere with, overload or try to gain unauthorized access to our servers, other accounts or the Service's security features.",
            "Record or analyze other people without their permission, or use the Service in a way that breaks any law.",
            "Share, sell or mass-generate friend codes or otherwise abuse promotions.",
            "Use the Service to build a competing product or train machine-learning models.",
          ]}
        />
      </>
    ),
  },
  {
    id: "safety",
    title: "Health and safety",
    body: (
      <p>
        Pickleball is a physical activity with a risk of injury. {SITE.product} gives practice feedback and is{" "}
        <Strong>not medical, physiotherapy or professional coaching advice</Strong>. Warm up, practice within your limits,
        and set up your phone where it won't cause a hazard. Scores and the Paddle Up Rating are estimates generated by
        software. They are not official DUPR ratings or any other official rating.
      </p>
    ),
  },
  {
    id: "subscriptions",
    title: "Subscriptions and billing",
    body: (
      <LegalList
        items={[
          <>
            <Strong>Billed by Apple.</Strong> {SITE.product} Pro is an auto-renewing subscription purchased through the
            App Store and charged to your Apple Account. Apple's terms and payment policies also apply.
          </>,
          <>
            <Strong>Auto-renewal.</Strong> Your subscription renews automatically at the end of each period (monthly or
            annual) at the then-current price, unless you cancel at least 24 hours before the period ends.
          </>,
          <>
            <Strong>Cancel anytime.</Strong> Manage or cancel on your iPhone under Settings → your name → Subscriptions,
            or in your Apple ID settings. Canceling stops future renewals. You keep Pro until the end of the period
            you've paid for.
          </>,
          <>
            <Strong>Refunds</Strong> are handled by Apple under its refund policies. We can't issue App Store refunds
            directly.
          </>,
          <>
            <Strong>Codes.</Strong> App Store offer codes are subject to Apple's terms. Friend codes give the free access
            stated when you redeem them, have no cash value, and may be limited, expire or be deactivated.
          </>,
          <>
            <Strong>Price changes</Strong> will be communicated in advance as required by Apple and applicable law.
          </>,
        ]}
      />
    ),
  },
  {
    id: "accounts",
    title: "Accounts and your data",
    body: (
      <p>
        Cloud sync is optional and uses Sign in with Apple or Google. You're responsible for activity on your account.
        You keep ownership of the data you create. You give us permission to store and process it only to provide the
        Service, as described in the Privacy Policy. You can delete your data at any time from the app.
      </p>
    ),
  },
  {
    id: "no-warranty",
    title: "No warranty",
    body: (
      <p className="uppercase tracking-[0.01em]">
        The Service is provided "as is" and "as available", without warranties of any kind, express or implied,
        including warranties of merchantability, fitness for a particular purpose, accuracy and non-infringement. We
        don't guarantee that the Service will be uninterrupted or error-free, that rep detection or scores will be
        accurate, or that using it will improve your play.
      </p>
    ),
  },
  {
    id: "liability",
    title: "Limitation of liability",
    body: (
      <p className="uppercase tracking-[0.01em]">
        To the fullest extent permitted by law, {SITE.company} will not be liable for any indirect, incidental, special,
        consequential or punitive damages, or for any loss of data, profits or goodwill, or for personal injury arising
        from physical activity, in connection with the Service. Our total liability for any claim relating to the Service
        is limited to the amount you paid for the Service in the 12 months before the claim, or US $50, whichever is
        greater. Some jurisdictions don't allow these limits, so they may not fully apply to you.
      </p>
    ),
  },
  {
    id: "termination",
    title: "Suspension and termination",
    body: (
      <p>
        You can stop using the Service at any time. We may suspend or end your access if you seriously or repeatedly
        break these Terms. Sections that by their nature should survive (such as ownership, disclaimers and limitation of
        liability) survive termination.
      </p>
    ),
  },
  {
    id: "apple",
    title: "Apple",
    body: (
      <p>
        These Terms are between you and {SITE.company}, not Apple. Apple is not responsible for the app or its content,
        has no obligation to provide maintenance or support for it, and is not responsible for any product claims.
        Apple and its subsidiaries are third-party beneficiaries of these Terms and may enforce them against you.
      </p>
    ),
  },
  {
    id: "changes",
    title: "Changes and governing law",
    body: (
      <p>
        We may update these Terms from time to time and will revise the "Last updated" date above. Material changes will
        be announced in the app. Continuing to use the Service after changes take effect means you accept them. These
        Terms are governed by the laws of the State of [STATE], United States, without regard to conflict-of-law rules.
      </p>
    ),
  },
  {
    id: "contact",
    title: "Contact",
    body: (
      <p>
        Questions about these Terms? Email {email}.
      </p>
    ),
  },
];

export default function Terms() {
  usePageTitle("Terms of Use");

  return (
    <LegalPage
      eyebrow={`${SITE.product} · Legal`}
      title="Terms of Use"
      intro={
        <>
          <p>The rules for using the {SITE.product} app and this website, in plain language.</p>
          <p className="rounded-2xl border border-[#FFB020]/25 bg-[#FFB020]/[0.07] px-4 py-3 text-[14px] text-[#FFD27A]">
            Draft pending legal review. These terms are a working version and may be revised.
          </p>
        </>
      }
      sections={SECTIONS}
    />
  );
}
